# Generated by Django 2.0.4 on 2018-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardwareManagment', '0002_vendor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='date_discard',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='made_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
